export const leaveRequests=[
    {
      id: 1,
      employeeName: "abc",
      employeeEmail: "abc@gmail.com",
      supervisorName: "Amey Karkare",
      supervisorEmail: "karkare@iitk.ac.in",
      leaveReason: "Going home",
      fromDate: "15/08/2025",
      toDate: "20/08/2025",
      time: "12/10/2022",
      action: "pending",
    },
    {
      id: 2,
      employeeName: "def",
      employeeEmail: "def@gmail.com",
      supervisorName: "Amey Karkare",
      supervisorEmail: "karkare@iitk.ac.in",
      leaveReason: "Sick Leave",
      fromDate: "15/08/2025",
      toDate: "20/08/2025",
      time: "02/10/2022",
      action: "pending",
    },
    {
      id: 3,
      employeeName: "tdsbn",
      employeeEmail: "tds@gmail.com",
      supervisorName: "Amey Karkare",
      supervisorEmail: "karkare@iitk.ac.in",
      leaveReason: "Casual Leave",
      fromDate: "15/08/2025",
      toDate: "20/08/2025",
      time: "10/05/2021",
      action: "accepted",
    },
    {
      id: 4,
      employeeName: "kdhiai",
      employeeEmail: "kdhi@gmail.com",
      supervisorName: "Amey Karkare",
      supervisorEmail: "karkare@iitk.ac.in",
      leaveReason: "Leave to go home",
      fromDate: "15/08/2025",
      toDate: "20/08/2025",
      time: "08/02/2021",
      action: "rejected",
    },
    {
      id: 5,
      employeeName: "hdkej",
      employeeEmail: "hd@gmail.com",
      supervisorName: "Amey Karkare",
      supervisorEmail: "karkare@iitk.ac.in",
      leaveReason: "Casual Leave",
      fromDate: "15/08/2025",
      toDate: "20/08/2025",
      time: "15/11/2020",
      action: "accepted",
    },
  ];